apiVersion: miren.dev/rpc/v1
kind: IDL

imports:
  stream:
    path: ../pkg/rpc/stream/stream.yml
    import: miren.dev/runtime/pkg/rpc/stream

types:
  - type: WindowSize
    fields:
      - name: height
        type: int32
        index: 0
      - name: width
        type: int32
        index: 1
  - type: ShellOptions
    fields:
      - name: terminal
        type: bool
        index: 0
      - name: command
        type: list
        element: string
        index: 1
      - name: win_size
        type: WindowSize
        index: 2
      - name: env
        type: list
        element: string
        index: 3
      - name: pool
        type: string
        index: 4

interfaces:
  - name: ShellAccess
    methods:
      - name: open
        parameters:
          - name: application
            type: string
          - name: options
            type: ShellOptions
          - name: input
            type: stream.RecvStream[[]byte]
          - name: output
            type: stream.SendStream[[]byte]
          - name: window_updates
            type: stream.RecvStream[*WindowSize]
        results:
          - name: status
            type: int32

