domain: dev.miren.compute
version: v1alpha

components:
  # Immutable build-time sandbox configuration
  # Shared between Sandbox (as spec field) and SandboxPool (as template)
  sandbox_spec:
    version:
      type: ref
      doc: Application version reference

    logEntity:
      type: string
      doc: Entity to associate log output with

    logAttribute:
      type: label
      doc: Labels for log entries
      many: true

    hostNetwork:
      type: bool
      doc: Whether to use host networking

    route:
      type: component
      doc: Network route configuration
      many: true
      attrs:
        destination:
          type: string
          doc: Network destination
        gateway:
          type: string
          doc: Next hop for destination

    volume:
      type: component
      doc: Volume configuration
      many: true
      attrs:
        name:
          type: string
          doc: Volume name
        provider:
          type: string
          doc: Volume provider
        labels:
          type: label
          doc: Labels identifying the volume
          many: true

    static_host:
      type: component
      doc: Static host-to-IP mapping
      many: true
      attrs:
        host:
          type: string
          doc: Hostname
        ip:
          type: string
          doc: IP address

    container:
      type: component
      doc: Container specification
      many: true
      required: true
      attrs:
        image:
          type: string
          doc: Container image
          required: true
        name:
          type: string
          doc: Container name
        privileged:
          type: bool
          doc: Whether container runs in privileged mode
        command:
          type: string
          doc: Command to run
        directory:
          type: string
          doc: Working directory
        env:
          type: string
          doc: Environment variable
          many: true
        port:
          type: component
          doc: Network port declaration
          many: true
          attrs:
            port:
              type: int
              doc: Port number
              required: true
            name:
              type: string
              doc: Port name
              required: true
            protocol:
              type: enum
              doc: Port protocol
              choices: [tcp, udp]
            type:
              type: string
              doc: High-level port type (e.g., http)
            node_port:
              type: int
              doc: The port number that should be forwarded from the node to the container
        mount:
          type: component
          doc: Mounted directory
          many: true
          attrs:
            source:
              type: string
              doc: Mount source path
            destination:
              type: string
              doc: Mount destination path
        oom_score:
          type: int
          doc: OOM score adjustment
        config_file:
          type: component
          doc: File to write into container
          many: true
          attrs:
            path:
              type: string
              doc: File path in container
            data:
              type: string
              doc: File contents
            mode:
              type: string
              doc: File mode

kinds:
  sandbox:
    # Runtime fields
    status:
      type: enum
      doc: The status of the pod
      choices: [pending, not_ready, running, stopped, dead]

    last_activity:
      type: time
      doc: Last lease activity (throttled updates, ~30s granularity for scale-down)

    # Network is runtime field (address allocated by controller)
    network:
      type: component
      doc: Network accessability for the container
      many: true
      attrs:
        address:
          doc: A network address to reach the container at
          type: string
        subnet:
          doc: The subnet that the address is associated with
          type: string

    # Legacy fields - kept for backward compatibility with existing sandboxes
    # New sandboxes should use spec field instead
    labels:
      type: string
      doc: Label for the sandbox
      many: true

    hostNetwork:
      type: bool
      doc: |
        Indicates if the container should use the networking of
        node that it is running on directly

    logEntity:
      type: string
      doc: The entity to associate the log output of the sandbox with

    logAttribute:
      type: label
      doc: Labels that will be associated with the log entries generated by the sandbox
      many: true

    version:
      type: ref
      doc: A reference to the application version entity for the sandbox
      indexed: true

    route:
      type: component
      doc: A network route the container uses
      many: true
      attrs:
        destination:
          doc: The network destination
          type: string
        gateway:
          doc: The next hop for the destination
          type: string

    volume:
      type: component
      doc: A volume that is available for binding into containers
      many: true
      attrs:
        name:
          type: string
          doc: The name of the volume
        provider:
          type: string
          doc: What provider should provide the volume
        labels:
          type: label
          doc: Labels that identify the volume to the provider
          many: true

    static_host:
      type: component
      doc: A name to ip mapping configured staticly for the sandbox
      many: true
      attrs:
        host:
          type: string
          doc: The hostname
        ip:
          type: string
          doc: The IP

    container:
      type: component
      doc: A container running in the sandbox
      many: true
      required: true
      attrs:
        image:
          type: string
          doc: Container image
          required: true
        name:
          type: string
          doc: Container name
        privileged:
          type: bool
          doc: Whether or not the container runs in privileged mode
        command:
          type: string
          doc: Command to run in the container
        directory:
          type: string
          doc: Directory to start in
        env:
          type: string
          doc: Environment variable for the container
          many: true

        port:
          type: component
          doc: A network port the container declares
          many: true
          attrs:
            port:
              type: int
              doc: Port number
              required: true
            name:
              type: string
              doc: Name of the port for reference
              required: true
            protocol:
              type: enum
              doc: Port protocol
              choices: [tcp, udp]
            type:
              type: string
              doc: The highlevel type of the port
              example: http
            node_port:
              type: int
              doc: The port number that should be forwarded from the node to the container

        mount:
          type: component
          doc: A mounted directory
          many: true
          attrs:
            source:
              type: string
              doc: Mount source path
            destination:
              type: string
              doc: Mount destination path

        oom_score:
          type: int
          doc: How to adjust the OOM score for this container

        config_file:
          type: component
          doc: A file to write into the container before starting
          many: true
          attrs:
            path:
              type: string
              doc: The path in the container to write the data
            data:
              type: string
              doc: The configuration data
            mode:
              type: string
              doc: The file mode to set the configuration to

    # Immutable config - reference to standalone component (for new sandboxes)
    spec:
      type: sandbox_spec
      doc: Immutable sandbox configuration

  sandbox_pool:
    service:
      type: string
      doc: Service name (e.g., web, worker) - pool identifier
      indexed: true

    # Template for creating sandboxes - references same component as sandbox.spec
    sandbox_spec:
      type: sandbox_spec
      doc: Complete sandbox specification template

    # Concurrency/scaling configuration
    mode:
      type: enum
      doc: Concurrency mode
      choices: [auto, fixed]

    max_slots:
      type: int
      doc: For auto mode - max capacity per sandbox

    lease_slots:
      type: int
      doc: For auto mode - capacity allocated per lease

    scale_down_delay:
      type: duration
      doc: For auto mode - delay before retiring idle sandboxes

    # Desired state (managed by Activator)
    desired_instances:
      type: int
      doc: Target number of sandbox instances

    # Observable state (maintained by SandboxPoolManager)
    current_instances:
      type: int
      doc: Current number of sandbox instances

    ready_instances:
      type: int
      doc: Number of RUNNING sandboxes

  node:
    constraints:
      type: label
      doc: The label constraints the node has, used for scheduling
      many: true

    status:
      type: enum
      doc: The status of the node
      choices: [unknown, ready, disabled, unhealthy]
      session: true

    api_address:
      type: string
      doc: The address to connect the node at

  schedule:
    key:
      type: component
      doc: The scheduling key for an entity
      indexed: true
      attrs:
        node:
          type: ref
          doc: The node id the entity is scheduled for
        kind:
          type: ref
          doc: The type of entity this is

  lease:
    project:
      type: ref
      doc: Which project currently holds the lease
      indexed: true
    sandbox:
      type: ref
      doc: The sandbox that is leased
      indexed: true
    last_heartbeat:
      type: time
      doc: The last time the lease was updated

