# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
#
# For docs, see: https://docs.coderabbit.ai/getting-started/configure-coderabbit/
#
language: "en-US"
early_access: false
tone_instructions: |
  Be casual, friendly, and egoless, using approachable, clear, and conversational language that feels warm and engaging.
  Keep the writing light, concise, and positive, as if speaking to a peer.
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - "WIP"
chat:
  auto_reply: true
