version: "2"
linters:
  default: standard
  exclusions:
    warn-unused: true
    rules:
      - path: pkg/perf
        linters:
          - govet
        text: unreachable code
      - path: dataset/
        linters:
          - govet
        text: unreachable code
      - path: pkg/runsc/monitor
        linters:
          - govet
        text: unreachable code
      - path: pkg/entity/mock
        linters:
          - govet
        text: unreachable code
formatters:
  enable:
    - gofmt
    - goimports
