apiVersion: miren.dev/rpc/v1
kind: IDL

imports:
  stream:
    path: ../../pkg/rpc/stream/stream.yml
    import: miren.dev/runtime/pkg/rpc/stream
  entity:
    import: miren.dev/runtime/pkg/entity
    types:
      - Attr

types:
  - type: Entity
    fields:
      - name: id
        type: string
        index: 0
      - name: revision
        type: int64
        index: 1
      - name: created_at
        type: int64
        index: 2
      - name: updated_at
        type: int64
        index: 3
      - name: attrs
        type: list
        element: entity.Attr
        index: 4

  - type: EntityOp
    fields:
      - name: entity
        type: Entity
        index: 0
      - name: previous
        type: int64
        index: 1
      - name: operation
        type: int64
        index: 2
      - name: entity_id
        type: string
        index: 3

interfaces:
  - name: Stream
    methods:
      - name: recv
        parameters:
          - name: count
            type: int32
        results:
          - name: data
            type: bytes

  - name: EntityAccess
    methods:
      - name: get
        parameters:
          - name: id
            type: string
        results:
          - name: entity
            type: Entity

      - name: put
        parameters:
          - name: entity
            type: Entity
        results:
          - name: revision
            type: int64
          - name: id
            type: string

      - name: delete
        parameters:
          - name: id
            type: string
        results:
          - name: revision
            type: int64

      - name: watch_index
        parameters:
          - name: index
            type: entity.Attr
          - name: values
            type: stream.SendStream[*EntityOp]

      - name: list
        parameters:
          - name: index
            type: entity.Attr
        results:
          - name: values
            type: list
            element: Entity

      - name: parse
        parameters:
          - name: data
            type: bytes
        results:
          - name: entity
            type: Entity

      - name: format
        parameters:
          - name: entity
            type: Entity
        results:
          - name: data
            type: bytes
