domain: dev.miren.ingress
version: v1alpha
kinds:
  http_route:
    host:
      type: string
      doc: The hostname to match on for the application
      indexed: true
    app:
      type: ref
      doc: The application to route to
      indexed: true
      tags: [dev.miren.app_ref]
    default:
      type: bool
      indexed: true
      doc: Whether this is the default route for routing
