apiVersion: miren.dev/rpc/v1
kind: IDL
imports:
  stream:
    path: ../stream/stream.yml
    import: miren.dev/runtime/pkg/rpc/stream
types:
  - type: Reading
    fields:
      - name: temperature
        type: float32
        index: 0
      - name: seconds
        type: int32
        index: 1
      - name: meter
        type: string
        index: 2

  - type: Value
    fields:
      - name: v
        type: union
        union:
          - name: i
            index: 0
            type: int64
          - name: s
            index: 1
            type: string

interfaces:
  - name: Meter
    methods:
      - name: readTemperature
        index: 0
        parameters:
          - name: name
            type: string
        results:
          - name: reading
            type: Reading
      - name: getSetter
        index: 1
        parameters:
          - name: name
            type: string
        results:
          - name: setter
            type: SetTemp

  - name: SetTemp
    methods:
      - name: setTemp
        index: 0
        parameters:
          - name: temp
            type: int32
        results:
          - name: temp
            type: int32

  - name: UpdateReceiver
    methods:
      - name: update
        index: 0
        parameters:
          - name: reading
            type: Reading

  - name: MeterUpdates
    methods:
      - name: registerUpdates
        index: 0
        parameters:
          - name: recv
            type: UpdateReceiver

  - name: AdjustTemp
    methods:
      - name: adjust
        index: 0
        parameters:
          - name: setter
            type: SetTemp

  - name: SetTempG
    generic:
      - T
    methods:
      - name: setTemp
        parameters:
          - name: temp
            type: T

  - name: EmitTemps
    methods:
      - name: emit
        parameters:
          - name: emitter
            type: stream.SendStream[float32]
