// Code generated by labsgen. DO NOT EDIT.

package labs

import (
	"log/slog"
	"strings"
	"sync"
)

// Feature name constants
const (
	FeatureDistributedRunners = "distributedrunners"
	FeatureSagas              = "sagas"
)

// AllFeatures returns a list of all known feature names
func AllFeatures() []string {
	return []string{
		FeatureDistributedRunners,
		FeatureSagas,
	}
}

// FeatureDescriptions returns a map of feature names to their descriptions
func FeatureDescriptions() map[string]string {
	return map[string]string{
		FeatureDistributedRunners: "Schedule jobs across multiple runner nodes",
		FeatureSagas:              "Use saga-based crash-recoverable workflows",
	}
}

var (
	mu              sync.RWMutex
	enabledFeatures = make(map[string]bool)
)

// featureDefaults holds the default state for each feature
var featureDefaults = map[string]bool{
	FeatureDistributedRunners: false,
	FeatureSagas:              false,
}

// Init initializes the labs feature flags from the provided flag strings.
// Each flag can be a feature name to enable it, or prefixed with "-" to disable it.
// Unknown feature names are logged as warnings but do not cause an error.
// This function should be called once at startup.
func Init(log *slog.Logger, flags []string) {
	mu.Lock()
	defer mu.Unlock()

	// Start with defaults
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}

	for _, flag := range flags {
		flag = strings.TrimSpace(flag)
		if flag == "" {
			continue
		}

		disable := false
		name := flag
		if strings.HasPrefix(flag, "-") {
			disable = true
			name = strings.TrimPrefix(flag, "-")
		}

		// Normalize to lowercase for lookup
		name = strings.ToLower(name)

		// Handle the special "all" keyword
		if name == "all" {
			for featureName := range featureDefaults {
				enabledFeatures[featureName] = !disable
			}
			if log != nil {
				log.Info("labs feature configured", "feature", "all", "enabled", !disable)
			}
			continue
		}

		// Check if it's a known feature
		if _, known := featureDefaults[name]; !known {
			if log != nil {
				log.Warn("unknown labs feature flag", "flag", flag)
			}
			continue
		}

		enabledFeatures[name] = !disable
		if log != nil {
			log.Info("labs feature configured", "feature", name, "enabled", !disable)
		}
	}
}

// Reset resets the feature flags to their default state.
// This is primarily useful for testing.
func Reset() {
	mu.Lock()
	defer mu.Unlock()

	enabledFeatures = make(map[string]bool)
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}
}

// IsEnabled returns whether a feature is enabled.
// Returns the default value if Init has not been called.
func IsEnabled(name string) bool {
	mu.RLock()
	defer mu.RUnlock()

	name = strings.ToLower(name)
	if enabled, ok := enabledFeatures[name]; ok {
		return enabled
	}
	if defaultVal, ok := featureDefaults[name]; ok {
		return defaultVal
	}
	return false
}

// Feature predicate functions

// DistributedRunners returns whether the distributedrunners feature is enabled.
// Schedule jobs across multiple runner nodes
func DistributedRunners() bool {
	return IsEnabled(FeatureDistributedRunners)
}

// Sagas returns whether the sagas feature is enabled.
// Use saga-based crash-recoverable workflows
func Sagas() bool {
	return IsEnabled(FeatureSagas)
}
