// Code generated by labsgen. DO NOT EDIT.

package labs

import (
	"log/slog"
	"sort"
	"strings"
	"sync"
)

// Feature name constants
const (
	FeatureAppVisibility      = "appvisibility"
	FeatureDistributedRunners = "distributedrunners"
	FeatureSagas              = "sagas"
)

// AllFeatures returns a list of all known feature names
func AllFeatures() []string {
	return []string{
		FeatureAppVisibility,
		FeatureDistributedRunners,
		FeatureSagas,
	}
}

// FeatureDescriptions returns a map of feature names to their descriptions
func FeatureDescriptions() map[string]string {
	return map[string]string{
		FeatureAppVisibility:      "Negotiate app visibility protocols over the cloud uplink",
		FeatureDistributedRunners: "Schedule jobs across multiple runner nodes",
		FeatureSagas:              "Use saga-based crash-recoverable workflows",
	}
}

var (
	mu              sync.RWMutex
	enabledFeatures = make(map[string]bool)
)

// featureDefaults holds the default state for each feature
var featureDefaults = map[string]bool{
	FeatureAppVisibility:      false,
	FeatureDistributedRunners: true,
	FeatureSagas:              true,
}

// Init initializes the labs feature flags from the provided flag strings.
// Each flag can be a feature name to enable it, or prefixed with "-" to disable it.
// Unknown feature names are logged as warnings but do not cause an error.
// This function should be called once at startup.
//
// log is required; pass slog.New(slog.DiscardHandler) to silence it.
func Init(log *slog.Logger, flags []string) {
	mu.Lock()
	defer mu.Unlock()

	// Start with defaults
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}

	for _, flag := range flags {
		flag = strings.TrimSpace(flag)
		if flag == "" {
			continue
		}

		disable := false
		name := flag
		if strings.HasPrefix(flag, "-") {
			disable = true
			name = strings.TrimPrefix(flag, "-")
		}

		// Normalize to lowercase for lookup
		name = strings.ToLower(name)

		// Handle the special "all" keyword
		if name == "all" {
			for featureName := range featureDefaults {
				enabledFeatures[featureName] = !disable
			}
			continue
		}

		// Check if it's a known feature
		if _, known := featureDefaults[name]; !known {
			log.Warn("unknown labs feature flag", "flag", flag)
			continue
		}

		enabledFeatures[name] = !disable
	}

	// Report where every feature landed, not just the ones that were named.
	// Features that default to on say nothing on their own, so without this
	// the boot log is silent about the state an operator most wants to see.
	names := AllFeatures()
	sort.Strings(names)

	attrs := make([]any, 0, len(names)*2)
	for _, name := range names {
		// Read the map directly: IsEnabled takes the read lock we already hold.
		attrs = append(attrs, name, enabledFeatures[name])
	}

	log.Info("labs features", attrs...)
}

// Reset resets the feature flags to their default state.
// This is primarily useful for testing.
func Reset() {
	mu.Lock()
	defer mu.Unlock()

	enabledFeatures = make(map[string]bool)
	for name, defaultVal := range featureDefaults {
		enabledFeatures[name] = defaultVal
	}
}

// IsEnabled returns whether a feature is enabled.
// Returns the default value if Init has not been called.
func IsEnabled(name string) bool {
	mu.RLock()
	defer mu.RUnlock()

	name = strings.ToLower(name)
	if enabled, ok := enabledFeatures[name]; ok {
		return enabled
	}
	if defaultVal, ok := featureDefaults[name]; ok {
		return defaultVal
	}
	return false
}

// Feature predicate functions

// AppVisibility returns whether the appvisibility feature is enabled.
// Negotiate app visibility protocols over the cloud uplink
func AppVisibility() bool {
	return IsEnabled(FeatureAppVisibility)
}

// DistributedRunners returns whether the distributedrunners feature is enabled.
// Schedule jobs across multiple runner nodes
func DistributedRunners() bool {
	return IsEnabled(FeatureDistributedRunners)
}

// Sagas returns whether the sagas feature is enabled.
// Use saga-based crash-recoverable workflows
func Sagas() bool {
	return IsEnabled(FeatureSagas)
}
