#!/usr/bin/env bash

# Usage: ./hack/run <package> <test-pattern> [additional go test flags...]
# Example: ./hack/run miren.dev/runtime/lsvd TestTortureQuick -torture.seed=12345

pkg="$1"
pattern="$2"
shift 2

iso run VERBOSE=1 -- bash hack/test.sh "$pkg" -run "$pattern" "$@"
