package commands

import (
	"log/slog"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWriteDevClusterConfig(t *testing.T) {
	// Create a temporary home directory
	tmpHome := t.TempDir()

	// Save original HOME and restore after test
	origHome := os.Getenv("HOME")
	os.Setenv("HOME", tmpHome)
	defer os.Setenv("HOME", origHome)

	// Also clear SUDO_USER for this test
	origSudoUser := os.Getenv("SUDO_USER")
	os.Unsetenv("SUDO_USER")
	defer func() {
		if origSudoUser != "" {
			os.Setenv("SUDO_USER", origSudoUser)
		}
	}()

	// Create a test context
	ctx := &Context{
		Log: slog.New(slog.NewTextHandler(os.Stderr, nil)),
	}

	// Test writing the config
	address := "localhost:8443"
	err := writeDevClusterConfig(ctx, address)
	require.NoError(t, err)

	// Verify the file was created
	configPath := filepath.Join(tmpHome, ".config/runtime/clientconfig.d/50-dev.yaml")
	assert.FileExists(t, configPath)

	// Read and verify the content
	content, err := os.ReadFile(configPath)
	require.NoError(t, err)

	expectedContent := `# Auto-generated by 'runtime dev' - DO NOT EDIT
clusters:
  dev:
    hostname: localhost:8443
    insecure: true
`
	assert.Equal(t, expectedContent, string(content))
}

func TestWriteDevClusterConfig_WithSudoUser(t *testing.T) {
	// Skip if running as root
	if os.Geteuid() == 0 {
		t.Skip("Test cannot run as root")
	}

	// Create two temporary directories - one for sudo HOME, one for regular user
	tmpSudoHome := t.TempDir()
	tmpUserHome := t.TempDir()

	// Save original env vars
	origHome := os.Getenv("HOME")
	origSudoUser := os.Getenv("SUDO_USER")

	// Set up test environment
	os.Setenv("HOME", tmpSudoHome)
	os.Setenv("SUDO_USER", "testuser")

	// Mock the user lookup by creating the expected directory structure
	// In real usage, user.Lookup would find the actual user's home
	expectedConfigDir := filepath.Join(tmpUserHome, ".config/runtime/clientconfig.d")
	err := os.MkdirAll(expectedConfigDir, 0755)
	require.NoError(t, err)

	defer func() {
		os.Setenv("HOME", origHome)
		if origSudoUser != "" {
			os.Setenv("SUDO_USER", origSudoUser)
		} else {
			os.Unsetenv("SUDO_USER")
		}
	}()

	// Note: This test is limited because we can't easily mock user.Lookup
	// In practice, the function would use the SUDO_USER's actual home directory
}
