// Code generated by configgen. DO NOT EDIT.

package serverconfig

import (
	"time"
)

// BuildkitConfig BuildKit daemon configuration
type BuildkitConfig struct {
	GcKeepDuration *string `toml:"gc_keep_duration" env:"MIREN_BUILDKIT_GC_KEEP_DURATION"`
	GcKeepStorage  *string `toml:"gc_keep_storage" env:"MIREN_BUILDKIT_GC_KEEP_STORAGE"`
	SocketDir      *string `toml:"socket_dir" env:"MIREN_BUILDKIT_SOCKET_DIR"`
	StartEmbedded  *bool   `toml:"start_embedded" env:"MIREN_BUILDKIT_START_EMBEDDED"`
}

// GetGcKeepDuration returns the value of GcKeepDuration or its zero value if nil
func (c *BuildkitConfig) GetGcKeepDuration() string {
	if c.GcKeepDuration != nil {
		return *c.GcKeepDuration
	}
	return ""
}

// SetGcKeepDuration sets the value of GcKeepDuration
func (c *BuildkitConfig) SetGcKeepDuration(v string) {
	c.GcKeepDuration = &v
}

// GetGcKeepStorage returns the value of GcKeepStorage or its zero value if nil
func (c *BuildkitConfig) GetGcKeepStorage() string {
	if c.GcKeepStorage != nil {
		return *c.GcKeepStorage
	}
	return ""
}

// SetGcKeepStorage sets the value of GcKeepStorage
func (c *BuildkitConfig) SetGcKeepStorage(v string) {
	c.GcKeepStorage = &v
}

// GetSocketDir returns the value of SocketDir or its zero value if nil
func (c *BuildkitConfig) GetSocketDir() string {
	if c.SocketDir != nil {
		return *c.SocketDir
	}
	return ""
}

// SetSocketDir sets the value of SocketDir
func (c *BuildkitConfig) SetSocketDir(v string) {
	c.SocketDir = &v
}

// GetStartEmbedded returns the value of StartEmbedded or its zero value if nil
func (c *BuildkitConfig) GetStartEmbedded() bool {
	if c.StartEmbedded != nil {
		return *c.StartEmbedded
	}
	return false
}

// SetStartEmbedded sets the value of StartEmbedded
func (c *BuildkitConfig) SetStartEmbedded(v bool) {
	c.StartEmbedded = &v
}

// Config Complete server configuration from all sources
type Config struct {
	Buildkit        BuildkitConfig        `toml:"buildkit"`
	Containerd      ContainerdConfig      `toml:"containerd"`
	Etcd            EtcdConfig            `toml:"etcd"`
	Mode            *string               `toml:"mode" env:"MIREN_MODE"`
	Server          ServerConfig          `toml:"server"`
	TLS             TLSConfig             `toml:"tls"`
	Victorialogs    VictoriaLogsConfig    `toml:"victorialogs"`
	Victoriametrics VictoriaMetricsConfig `toml:"victoriametrics"`
}

// GetMode returns the value of Mode or its zero value if nil
func (c *Config) GetMode() string {
	if c.Mode != nil {
		return *c.Mode
	}
	return ""
}

// SetMode sets the value of Mode
func (c *Config) SetMode(v string) {
	c.Mode = &v
}

// ContainerdConfig Containerd configuration
type ContainerdConfig struct {
	BinaryPath    *string `toml:"binary_path" env:"MIREN_CONTAINERD_BINARY_PATH"`
	SocketPath    *string `toml:"socket_path" env:"MIREN_CONTAINERD_SOCKET_PATH"`
	StartEmbedded *bool   `toml:"start_embedded" env:"MIREN_CONTAINERD_START_EMBEDDED"`
}

// GetBinaryPath returns the value of BinaryPath or its zero value if nil
func (c *ContainerdConfig) GetBinaryPath() string {
	if c.BinaryPath != nil {
		return *c.BinaryPath
	}
	return ""
}

// SetBinaryPath sets the value of BinaryPath
func (c *ContainerdConfig) SetBinaryPath(v string) {
	c.BinaryPath = &v
}

// GetSocketPath returns the value of SocketPath or its zero value if nil
func (c *ContainerdConfig) GetSocketPath() string {
	if c.SocketPath != nil {
		return *c.SocketPath
	}
	return ""
}

// SetSocketPath sets the value of SocketPath
func (c *ContainerdConfig) SetSocketPath(v string) {
	c.SocketPath = &v
}

// GetStartEmbedded returns the value of StartEmbedded or its zero value if nil
func (c *ContainerdConfig) GetStartEmbedded() bool {
	if c.StartEmbedded != nil {
		return *c.StartEmbedded
	}
	return false
}

// SetStartEmbedded sets the value of StartEmbedded
func (c *ContainerdConfig) SetStartEmbedded(v bool) {
	c.StartEmbedded = &v
}

// EtcdConfig Etcd configuration
type EtcdConfig struct {
	ClientPort     *int     `toml:"client_port" env:"MIREN_ETCD_CLIENT_PORT"`
	Endpoints      []string `toml:"endpoints" env:"MIREN_ETCD_ENDPOINTS"`
	HTTPClientPort *int     `toml:"http_client_port" env:"MIREN_ETCD_HTTP_CLIENT_PORT"`
	PeerPort       *int     `toml:"peer_port" env:"MIREN_ETCD_PEER_PORT"`
	Prefix         *string  `toml:"prefix" env:"MIREN_ETCD_PREFIX"`
	StartEmbedded  *bool    `toml:"start_embedded" env:"MIREN_ETCD_START_EMBEDDED"`
}

// GetClientPort returns the value of ClientPort or its zero value if nil
func (c *EtcdConfig) GetClientPort() int {
	if c.ClientPort != nil {
		return *c.ClientPort
	}
	return 0
}

// SetClientPort sets the value of ClientPort
func (c *EtcdConfig) SetClientPort(v int) {
	c.ClientPort = &v
}

// GetHTTPClientPort returns the value of HTTPClientPort or its zero value if nil
func (c *EtcdConfig) GetHTTPClientPort() int {
	if c.HTTPClientPort != nil {
		return *c.HTTPClientPort
	}
	return 0
}

// SetHTTPClientPort sets the value of HTTPClientPort
func (c *EtcdConfig) SetHTTPClientPort(v int) {
	c.HTTPClientPort = &v
}

// GetPeerPort returns the value of PeerPort or its zero value if nil
func (c *EtcdConfig) GetPeerPort() int {
	if c.PeerPort != nil {
		return *c.PeerPort
	}
	return 0
}

// SetPeerPort sets the value of PeerPort
func (c *EtcdConfig) SetPeerPort(v int) {
	c.PeerPort = &v
}

// GetPrefix returns the value of Prefix or its zero value if nil
func (c *EtcdConfig) GetPrefix() string {
	if c.Prefix != nil {
		return *c.Prefix
	}
	return ""
}

// SetPrefix sets the value of Prefix
func (c *EtcdConfig) SetPrefix(v string) {
	c.Prefix = &v
}

// GetStartEmbedded returns the value of StartEmbedded or its zero value if nil
func (c *EtcdConfig) GetStartEmbedded() bool {
	if c.StartEmbedded != nil {
		return *c.StartEmbedded
	}
	return false
}

// SetStartEmbedded sets the value of StartEmbedded
func (c *EtcdConfig) SetStartEmbedded(v bool) {
	c.StartEmbedded = &v
}

// ServerConfig Core server settings
type ServerConfig struct {
	Address                 *string `toml:"address" env:"MIREN_SERVER_ADDRESS"`
	ConfigClusterName       *string `toml:"config_cluster_name" env:"MIREN_SERVER_CONFIG_CLUSTER_NAME"`
	DataPath                *string `toml:"data_path" env:"MIREN_SERVER_DATA_PATH"`
	HTTPRequestTimeout      *int    `toml:"http_request_timeout" env:"MIREN_SERVER_HTTP_REQUEST_TIMEOUT"`
	ReleasePath             *string `toml:"release_path" env:"MIREN_SERVER_RELEASE_PATH"`
	RunnerAddress           *string `toml:"runner_address" env:"MIREN_SERVER_RUNNER_ADDRESS"`
	RunnerID                *string `toml:"runner_id" env:"MIREN_SERVER_RUNNER_ID"`
	SkipClientConfig        *bool   `toml:"skip_client_config" env:"MIREN_SERVER_SKIP_CLIENT_CONFIG"`
	StopSandboxesOnShutdown *bool   `toml:"stop_sandboxes_on_shutdown" env:"MIREN_SERVER_STOP_SANDBOXES_ON_SHUTDOWN"`
}

// GetAddress returns the value of Address or its zero value if nil
func (c *ServerConfig) GetAddress() string {
	if c.Address != nil {
		return *c.Address
	}
	return ""
}

// SetAddress sets the value of Address
func (c *ServerConfig) SetAddress(v string) {
	c.Address = &v
}

// GetConfigClusterName returns the value of ConfigClusterName or its zero value if nil
func (c *ServerConfig) GetConfigClusterName() string {
	if c.ConfigClusterName != nil {
		return *c.ConfigClusterName
	}
	return ""
}

// SetConfigClusterName sets the value of ConfigClusterName
func (c *ServerConfig) SetConfigClusterName(v string) {
	c.ConfigClusterName = &v
}

// GetDataPath returns the value of DataPath or its zero value if nil
func (c *ServerConfig) GetDataPath() string {
	if c.DataPath != nil {
		return *c.DataPath
	}
	return ""
}

// SetDataPath sets the value of DataPath
func (c *ServerConfig) SetDataPath(v string) {
	c.DataPath = &v
}

// GetHTTPRequestTimeout returns the value of HTTPRequestTimeout or its zero value if nil
func (c *ServerConfig) GetHTTPRequestTimeout() int {
	if c.HTTPRequestTimeout != nil {
		return *c.HTTPRequestTimeout
	}
	return 0
}

// SetHTTPRequestTimeout sets the value of HTTPRequestTimeout
func (c *ServerConfig) SetHTTPRequestTimeout(v int) {
	c.HTTPRequestTimeout = &v
}

// GetReleasePath returns the value of ReleasePath or its zero value if nil
func (c *ServerConfig) GetReleasePath() string {
	if c.ReleasePath != nil {
		return *c.ReleasePath
	}
	return ""
}

// SetReleasePath sets the value of ReleasePath
func (c *ServerConfig) SetReleasePath(v string) {
	c.ReleasePath = &v
}

// GetRunnerAddress returns the value of RunnerAddress or its zero value if nil
func (c *ServerConfig) GetRunnerAddress() string {
	if c.RunnerAddress != nil {
		return *c.RunnerAddress
	}
	return ""
}

// SetRunnerAddress sets the value of RunnerAddress
func (c *ServerConfig) SetRunnerAddress(v string) {
	c.RunnerAddress = &v
}

// GetRunnerID returns the value of RunnerID or its zero value if nil
func (c *ServerConfig) GetRunnerID() string {
	if c.RunnerID != nil {
		return *c.RunnerID
	}
	return ""
}

// SetRunnerID sets the value of RunnerID
func (c *ServerConfig) SetRunnerID(v string) {
	c.RunnerID = &v
}

// GetSkipClientConfig returns the value of SkipClientConfig or its zero value if nil
func (c *ServerConfig) GetSkipClientConfig() bool {
	if c.SkipClientConfig != nil {
		return *c.SkipClientConfig
	}
	return false
}

// SetSkipClientConfig sets the value of SkipClientConfig
func (c *ServerConfig) SetSkipClientConfig(v bool) {
	c.SkipClientConfig = &v
}

// GetStopSandboxesOnShutdown returns the value of StopSandboxesOnShutdown or its zero value if nil
func (c *ServerConfig) GetStopSandboxesOnShutdown() bool {
	if c.StopSandboxesOnShutdown != nil {
		return *c.StopSandboxesOnShutdown
	}
	return false
}

// SetStopSandboxesOnShutdown sets the value of StopSandboxesOnShutdown
func (c *ServerConfig) SetStopSandboxesOnShutdown(v bool) {
	c.StopSandboxesOnShutdown = &v
}

// TLSConfig TLS/certificate settings
type TLSConfig struct {
	AcmeDNSProvider *string  `toml:"acme_dns_provider" env:"MIREN_TLS_ACME_DNS_PROVIDER"`
	AcmeEmail       *string  `toml:"acme_email" env:"MIREN_TLS_ACME_EMAIL"`
	AdditionalIPs   []string `toml:"additional_ips" env:"MIREN_TLS_ADDITIONAL_IPS"`
	AdditionalNames []string `toml:"additional_names" env:"MIREN_TLS_ADDITIONAL_NAMES"`
	StandardTLS     *bool    `toml:"standard_tls" env:"MIREN_TLS_STANDARD_TLS"`
}

// GetAcmeDNSProvider returns the value of AcmeDNSProvider or its zero value if nil
func (c *TLSConfig) GetAcmeDNSProvider() string {
	if c.AcmeDNSProvider != nil {
		return *c.AcmeDNSProvider
	}
	return ""
}

// SetAcmeDNSProvider sets the value of AcmeDNSProvider
func (c *TLSConfig) SetAcmeDNSProvider(v string) {
	c.AcmeDNSProvider = &v
}

// GetAcmeEmail returns the value of AcmeEmail or its zero value if nil
func (c *TLSConfig) GetAcmeEmail() string {
	if c.AcmeEmail != nil {
		return *c.AcmeEmail
	}
	return ""
}

// SetAcmeEmail sets the value of AcmeEmail
func (c *TLSConfig) SetAcmeEmail(v string) {
	c.AcmeEmail = &v
}

// GetStandardTLS returns the value of StandardTLS or its zero value if nil
func (c *TLSConfig) GetStandardTLS() bool {
	if c.StandardTLS != nil {
		return *c.StandardTLS
	}
	return false
}

// SetStandardTLS sets the value of StandardTLS
func (c *TLSConfig) SetStandardTLS(v bool) {
	c.StandardTLS = &v
}

// VictoriaLogsConfig VictoriaLogs configuration
type VictoriaLogsConfig struct {
	Address         *string `toml:"address" env:"MIREN_VICTORIALOGS_ADDRESS"`
	HTTPPort        *int    `toml:"http_port" env:"MIREN_VICTORIALOGS_HTTP_PORT"`
	RetentionPeriod *string `toml:"retention_period" env:"MIREN_VICTORIALOGS_RETENTION_PERIOD"`
	StartEmbedded   *bool   `toml:"start_embedded" env:"MIREN_VICTORIALOGS_START_EMBEDDED"`
}

// GetAddress returns the value of Address or its zero value if nil
func (c *VictoriaLogsConfig) GetAddress() string {
	if c.Address != nil {
		return *c.Address
	}
	return ""
}

// SetAddress sets the value of Address
func (c *VictoriaLogsConfig) SetAddress(v string) {
	c.Address = &v
}

// GetHTTPPort returns the value of HTTPPort or its zero value if nil
func (c *VictoriaLogsConfig) GetHTTPPort() int {
	if c.HTTPPort != nil {
		return *c.HTTPPort
	}
	return 0
}

// SetHTTPPort sets the value of HTTPPort
func (c *VictoriaLogsConfig) SetHTTPPort(v int) {
	c.HTTPPort = &v
}

// GetRetentionPeriod returns the value of RetentionPeriod or its zero value if nil
func (c *VictoriaLogsConfig) GetRetentionPeriod() string {
	if c.RetentionPeriod != nil {
		return *c.RetentionPeriod
	}
	return ""
}

// SetRetentionPeriod sets the value of RetentionPeriod
func (c *VictoriaLogsConfig) SetRetentionPeriod(v string) {
	c.RetentionPeriod = &v
}

// GetStartEmbedded returns the value of StartEmbedded or its zero value if nil
func (c *VictoriaLogsConfig) GetStartEmbedded() bool {
	if c.StartEmbedded != nil {
		return *c.StartEmbedded
	}
	return false
}

// SetStartEmbedded sets the value of StartEmbedded
func (c *VictoriaLogsConfig) SetStartEmbedded(v bool) {
	c.StartEmbedded = &v
}

// VictoriaMetricsConfig VictoriaMetrics configuration
type VictoriaMetricsConfig struct {
	Address         *string `toml:"address" env:"MIREN_VICTORIAMETRICS_ADDRESS"`
	HTTPPort        *int    `toml:"http_port" env:"MIREN_VICTORIAMETRICS_HTTP_PORT"`
	RetentionPeriod *string `toml:"retention_period" env:"MIREN_VICTORIAMETRICS_RETENTION_PERIOD"`
	StartEmbedded   *bool   `toml:"start_embedded" env:"MIREN_VICTORIAMETRICS_START_EMBEDDED"`
}

// GetAddress returns the value of Address or its zero value if nil
func (c *VictoriaMetricsConfig) GetAddress() string {
	if c.Address != nil {
		return *c.Address
	}
	return ""
}

// SetAddress sets the value of Address
func (c *VictoriaMetricsConfig) SetAddress(v string) {
	c.Address = &v
}

// GetHTTPPort returns the value of HTTPPort or its zero value if nil
func (c *VictoriaMetricsConfig) GetHTTPPort() int {
	if c.HTTPPort != nil {
		return *c.HTTPPort
	}
	return 0
}

// SetHTTPPort sets the value of HTTPPort
func (c *VictoriaMetricsConfig) SetHTTPPort(v int) {
	c.HTTPPort = &v
}

// GetRetentionPeriod returns the value of RetentionPeriod or its zero value if nil
func (c *VictoriaMetricsConfig) GetRetentionPeriod() string {
	if c.RetentionPeriod != nil {
		return *c.RetentionPeriod
	}
	return ""
}

// SetRetentionPeriod sets the value of RetentionPeriod
func (c *VictoriaMetricsConfig) SetRetentionPeriod(v string) {
	c.RetentionPeriod = &v
}

// GetStartEmbedded returns the value of StartEmbedded or its zero value if nil
func (c *VictoriaMetricsConfig) GetStartEmbedded() bool {
	if c.StartEmbedded != nil {
		return *c.StartEmbedded
	}
	return false
}

// SetStartEmbedded sets the value of StartEmbedded
func (c *VictoriaMetricsConfig) SetStartEmbedded(v bool) {
	c.StartEmbedded = &v
}

// HTTPRequestTimeoutDuration returns the timeout as a time.Duration
func (c *ServerConfig) HTTPRequestTimeoutDuration() time.Duration {
	if c.HTTPRequestTimeout != nil {
		return time.Duration(*c.HTTPRequestTimeout) * time.Second
	}
	return 60 * time.Second // default
}
