// Code generated by configgen. DO NOT EDIT.

package serverconfig

// Helper functions for creating pointers to literals
func boolPtr(b bool) *bool    { return &b }
func intPtr(i int) *int       { return &i }
func strPtr(s string) *string { return &s }

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Buildkit:        DefaultBuildkitConfig(),
		Containerd:      DefaultContainerdConfig(),
		Etcd:            DefaultEtcdConfig(),
		Mode:            strPtr("standalone"),
		Server:          DefaultServerConfig(),
		TLS:             DefaultTLSConfig(),
		Victorialogs:    DefaultVictoriaLogsConfig(),
		Victoriametrics: DefaultVictoriaMetricsConfig(),
	}
}

// DefaultBuildkitConfig returns default BuildkitConfig
func DefaultBuildkitConfig() BuildkitConfig {
	return BuildkitConfig{
		GcKeepDuration: strPtr("7d"),
		GcKeepStorage:  strPtr("10GB"),
		SocketDir:      strPtr(""),
		SocketPath:     strPtr(""),
		StartEmbedded:  nil,
	}
}

// DefaultContainerdConfig returns default ContainerdConfig
func DefaultContainerdConfig() ContainerdConfig {
	return ContainerdConfig{
		BinaryPath:    strPtr("containerd"),
		SocketPath:    strPtr(""),
		StartEmbedded: nil,
	}
}

// DefaultEtcdConfig returns default EtcdConfig
func DefaultEtcdConfig() EtcdConfig {
	return EtcdConfig{
		ClientPort:     intPtr(12379),
		Endpoints:      []string{},
		HTTPClientPort: intPtr(12381),
		PeerPort:       intPtr(12380),
		Prefix:         strPtr("/miren"),
		StartEmbedded:  nil,
	}
}

// DefaultServerConfig returns default ServerConfig
func DefaultServerConfig() ServerConfig {
	return ServerConfig{
		Address:                 strPtr(":8443"),
		ConfigClusterName:       strPtr("local"),
		DataPath:                strPtr("/var/lib/miren"),
		HTTPRequestTimeout:      intPtr(60),
		ReleasePath:             strPtr(""),
		RunnerAddress:           strPtr("localhost:8444"),
		RunnerID:                strPtr("miren"),
		SkipClientConfig:        boolPtr(false),
		StopSandboxesOnShutdown: boolPtr(false),
	}
}

// DefaultTLSConfig returns default TLSConfig
func DefaultTLSConfig() TLSConfig {
	return TLSConfig{
		AcmeDNSProvider: strPtr(""),
		AcmeEmail:       strPtr(""),
		AdditionalIPs:   []string{},
		AdditionalNames: []string{},
		StandardTLS:     boolPtr(true),
	}
}

// DefaultVictoriaLogsConfig returns default VictoriaLogsConfig
func DefaultVictoriaLogsConfig() VictoriaLogsConfig {
	return VictoriaLogsConfig{
		Address:         strPtr("victorialogs:9428"),
		HTTPPort:        intPtr(9428),
		RetentionPeriod: strPtr("30d"),
		StartEmbedded:   nil,
	}
}

// DefaultVictoriaMetricsConfig returns default VictoriaMetricsConfig
func DefaultVictoriaMetricsConfig() VictoriaMetricsConfig {
	return VictoriaMetricsConfig{
		Address:         strPtr("victoriametrics:8428"),
		HTTPPort:        intPtr(8428),
		RetentionPeriod: strPtr("1"),
		StartEmbedded:   nil,
	}
}
