// Code generated by configgen. DO NOT EDIT.

package serverconfig

// Helper functions for creating pointers to literals
func boolPtr(b bool) *bool    { return &b }
func intPtr(i int) *int       { return &i }
func strPtr(s string) *string { return &s }

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Clickhouse: DefaultClickHouseConfig(),
		Containerd: DefaultContainerdConfig(),
		Etcd:       DefaultEtcdConfig(),
		Mode:       strPtr("standalone"),
		Server:     DefaultServerConfig(),
		TLS:        DefaultTLSConfig(),
	}
}

// DefaultClickHouseConfig returns default ClickHouseConfig
func DefaultClickHouseConfig() ClickHouseConfig {
	return ClickHouseConfig{
		Address:         strPtr(""),
		HTTPPort:        intPtr(8223),
		InterserverPort: intPtr(9010),
		NativePort:      intPtr(9009),
		StartEmbedded:   nil,
	}
}

// DefaultContainerdConfig returns default ContainerdConfig
func DefaultContainerdConfig() ContainerdConfig {
	return ContainerdConfig{
		BinaryPath:    strPtr("containerd"),
		SocketPath:    strPtr(""),
		StartEmbedded: nil,
	}
}

// DefaultEtcdConfig returns default EtcdConfig
func DefaultEtcdConfig() EtcdConfig {
	return EtcdConfig{
		ClientPort:     intPtr(12379),
		Endpoints:      []string{},
		HTTPClientPort: intPtr(12381),
		PeerPort:       intPtr(12380),
		Prefix:         strPtr("/miren"),
		StartEmbedded:  nil,
	}
}

// DefaultServerConfig returns default ServerConfig
func DefaultServerConfig() ServerConfig {
	return ServerConfig{
		Address:            strPtr("localhost:8443"),
		ConfigClusterName:  strPtr("local"),
		DataPath:           strPtr("/var/lib/miren"),
		HTTPRequestTimeout: intPtr(60),
		ReleasePath:        strPtr(""),
		RunnerAddress:      strPtr("localhost:8444"),
		RunnerID:           strPtr("miren"),
		SkipClientConfig:   boolPtr(false),
	}
}

// DefaultTLSConfig returns default TLSConfig
func DefaultTLSConfig() TLSConfig {
	return TLSConfig{
		AdditionalIPs:   []string{},
		AdditionalNames: []string{},
		StandardTLS:     boolPtr(false),
	}
}
