// Code generated by configgen. DO NOT EDIT.

package serverconfig

import (
	"log/slog"
	"os"
	"strconv"
	"strings"
)

// applyEnvironmentVariables applies environment variables to the configuration
func applyEnvironmentVariables(cfg *Config, log *slog.Logger) error {

	// Apply MIREN_CLICKHOUSE_ADDRESS
	if val := os.Getenv("MIREN_CLICKHOUSE_ADDRESS"); val != "" {

		cfg.Clickhouse.Address = val

		log.Debug("applied env var", "key", "MIREN_CLICKHOUSE_ADDRESS", "value", val)
	}

	// Apply MIREN_CLICKHOUSE_HTTP_PORT
	if val := os.Getenv("MIREN_CLICKHOUSE_HTTP_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Clickhouse.HttpPort = i
		} else {
			log.Warn("invalid MIREN_CLICKHOUSE_HTTP_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_CLICKHOUSE_HTTP_PORT", "value", val)
	}

	// Apply MIREN_CLICKHOUSE_INTERSERVER_PORT
	if val := os.Getenv("MIREN_CLICKHOUSE_INTERSERVER_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Clickhouse.InterserverPort = i
		} else {
			log.Warn("invalid MIREN_CLICKHOUSE_INTERSERVER_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_CLICKHOUSE_INTERSERVER_PORT", "value", val)
	}

	// Apply MIREN_CLICKHOUSE_NATIVE_PORT
	if val := os.Getenv("MIREN_CLICKHOUSE_NATIVE_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Clickhouse.NativePort = i
		} else {
			log.Warn("invalid MIREN_CLICKHOUSE_NATIVE_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_CLICKHOUSE_NATIVE_PORT", "value", val)
	}

	// Apply MIREN_CLICKHOUSE_START_EMBEDDED
	if val := os.Getenv("MIREN_CLICKHOUSE_START_EMBEDDED"); val != "" {

		cfg.Clickhouse.StartEmbedded = val == "true" || val == "1" || val == "yes"

		log.Debug("applied env var", "key", "MIREN_CLICKHOUSE_START_EMBEDDED", "value", val)
	}

	// Apply MIREN_MODE
	if val := os.Getenv("MIREN_MODE"); val != "" {

		cfg.Mode = val

		log.Debug("applied env var", "key", "MIREN_MODE", "value", val)
	}

	// Apply MIREN_CONTAINERD_BINARY_PATH
	if val := os.Getenv("MIREN_CONTAINERD_BINARY_PATH"); val != "" {

		cfg.Containerd.BinaryPath = val

		log.Debug("applied env var", "key", "MIREN_CONTAINERD_BINARY_PATH", "value", val)
	}

	// Apply MIREN_CONTAINERD_SOCKET_PATH
	if val := os.Getenv("MIREN_CONTAINERD_SOCKET_PATH"); val != "" {

		cfg.Containerd.SocketPath = val

		log.Debug("applied env var", "key", "MIREN_CONTAINERD_SOCKET_PATH", "value", val)
	}

	// Apply MIREN_CONTAINERD_START_EMBEDDED
	if val := os.Getenv("MIREN_CONTAINERD_START_EMBEDDED"); val != "" {

		cfg.Containerd.StartEmbedded = val == "true" || val == "1" || val == "yes"

		log.Debug("applied env var", "key", "MIREN_CONTAINERD_START_EMBEDDED", "value", val)
	}

	// Apply MIREN_ETCD_CLIENT_PORT
	if val := os.Getenv("MIREN_ETCD_CLIENT_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Etcd.ClientPort = i
		} else {
			log.Warn("invalid MIREN_ETCD_CLIENT_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_ETCD_CLIENT_PORT", "value", val)
	}

	// Apply MIREN_ETCD_ENDPOINTS
	if val := os.Getenv("MIREN_ETCD_ENDPOINTS"); val != "" {

		cfg.Etcd.Endpoints = strings.Split(val, ",")

		log.Debug("applied env var", "key", "MIREN_ETCD_ENDPOINTS", "value", val)
	}

	// Apply MIREN_ETCD_HTTP_CLIENT_PORT
	if val := os.Getenv("MIREN_ETCD_HTTP_CLIENT_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Etcd.HttpClientPort = i
		} else {
			log.Warn("invalid MIREN_ETCD_HTTP_CLIENT_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_ETCD_HTTP_CLIENT_PORT", "value", val)
	}

	// Apply MIREN_ETCD_PEER_PORT
	if val := os.Getenv("MIREN_ETCD_PEER_PORT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Etcd.PeerPort = i
		} else {
			log.Warn("invalid MIREN_ETCD_PEER_PORT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_ETCD_PEER_PORT", "value", val)
	}

	// Apply MIREN_ETCD_PREFIX
	if val := os.Getenv("MIREN_ETCD_PREFIX"); val != "" {

		cfg.Etcd.Prefix = val

		log.Debug("applied env var", "key", "MIREN_ETCD_PREFIX", "value", val)
	}

	// Apply MIREN_ETCD_START_EMBEDDED
	if val := os.Getenv("MIREN_ETCD_START_EMBEDDED"); val != "" {

		cfg.Etcd.StartEmbedded = val == "true" || val == "1" || val == "yes"

		log.Debug("applied env var", "key", "MIREN_ETCD_START_EMBEDDED", "value", val)
	}

	// Apply MIREN_SERVER_ADDRESS
	if val := os.Getenv("MIREN_SERVER_ADDRESS"); val != "" {

		cfg.Server.Address = val

		log.Debug("applied env var", "key", "MIREN_SERVER_ADDRESS", "value", val)
	}

	// Apply MIREN_SERVER_CONFIG_CLUSTER_NAME
	if val := os.Getenv("MIREN_SERVER_CONFIG_CLUSTER_NAME"); val != "" {

		cfg.Server.ConfigClusterName = val

		log.Debug("applied env var", "key", "MIREN_SERVER_CONFIG_CLUSTER_NAME", "value", val)
	}

	// Apply MIREN_SERVER_DATA_PATH
	if val := os.Getenv("MIREN_SERVER_DATA_PATH"); val != "" {

		cfg.Server.DataPath = val

		log.Debug("applied env var", "key", "MIREN_SERVER_DATA_PATH", "value", val)
	}

	// Apply MIREN_SERVER_HTTP_REQUEST_TIMEOUT
	if val := os.Getenv("MIREN_SERVER_HTTP_REQUEST_TIMEOUT"); val != "" {

		if i, err := strconv.Atoi(val); err == nil {
			cfg.Server.HttpRequestTimeout = i
		} else {
			log.Warn("invalid MIREN_SERVER_HTTP_REQUEST_TIMEOUT value", "value", val, "error", err)
		}

		log.Debug("applied env var", "key", "MIREN_SERVER_HTTP_REQUEST_TIMEOUT", "value", val)
	}

	// Apply MIREN_SERVER_RELEASE_PATH
	if val := os.Getenv("MIREN_SERVER_RELEASE_PATH"); val != "" {

		cfg.Server.ReleasePath = val

		log.Debug("applied env var", "key", "MIREN_SERVER_RELEASE_PATH", "value", val)
	}

	// Apply MIREN_SERVER_RUNNER_ADDRESS
	if val := os.Getenv("MIREN_SERVER_RUNNER_ADDRESS"); val != "" {

		cfg.Server.RunnerAddress = val

		log.Debug("applied env var", "key", "MIREN_SERVER_RUNNER_ADDRESS", "value", val)
	}

	// Apply MIREN_SERVER_RUNNER_ID
	if val := os.Getenv("MIREN_SERVER_RUNNER_ID"); val != "" {

		cfg.Server.RunnerId = val

		log.Debug("applied env var", "key", "MIREN_SERVER_RUNNER_ID", "value", val)
	}

	// Apply MIREN_SERVER_SKIP_CLIENT_CONFIG
	if val := os.Getenv("MIREN_SERVER_SKIP_CLIENT_CONFIG"); val != "" {

		cfg.Server.SkipClientConfig = val == "true" || val == "1" || val == "yes"

		log.Debug("applied env var", "key", "MIREN_SERVER_SKIP_CLIENT_CONFIG", "value", val)
	}

	// Apply MIREN_TLS_ADDITIONAL_IPS
	if val := os.Getenv("MIREN_TLS_ADDITIONAL_IPS"); val != "" {

		cfg.Tls.AdditionalIps = strings.Split(val, ",")

		log.Debug("applied env var", "key", "MIREN_TLS_ADDITIONAL_IPS", "value", val)
	}

	// Apply MIREN_TLS_ADDITIONAL_NAMES
	if val := os.Getenv("MIREN_TLS_ADDITIONAL_NAMES"); val != "" {

		cfg.Tls.AdditionalNames = strings.Split(val, ",")

		log.Debug("applied env var", "key", "MIREN_TLS_ADDITIONAL_NAMES", "value", val)
	}

	// Apply MIREN_TLS_STANDARD_TLS
	if val := os.Getenv("MIREN_TLS_STANDARD_TLS"); val != "" {

		cfg.Tls.StandardTls = val == "true" || val == "1" || val == "yes"

		log.Debug("applied env var", "key", "MIREN_TLS_STANDARD_TLS", "value", val)
	}

	return nil
}
