// Code generated by configgen. DO NOT EDIT.

package serverconfig

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
	"miren.dev/mflags"
)

// Load loads configuration from all sources with proper precedence:
// CLI flags > Environment variables > Config file > Defaults
//
// Environment variables are applied via mflags' env:"..." struct tags on
// CLIFlags. When flags is nil, Load materializes a CLIFlags from env vars
// so callers (typically tests) that only set env still see the same
// precedence as the CLI path.
func Load(configPath string, flags *CLIFlags, log *slog.Logger) (*Config, error) {
	if log == nil {
		log = slog.Default()
	}

	if flags == nil {
		flags = NewCLIFlags()
		fs := mflags.NewFlagSet("serverconfig")
		if err := fs.FromStruct(flags); err != nil {
			return nil, fmt.Errorf("failed to wire CLIFlags for env application: %w", err)
		}
	}

	cfg := DefaultConfig()

	// Determine data path for config discovery with proper precedence
	// CLI/env (carried by flags) > Defaults
	var dataPathForSearch string
	if cfg.Server.DataPath != nil {
		dataPathForSearch = *cfg.Server.DataPath
	}
	if flags.ServerConfigDataPath != nil && *flags.ServerConfigDataPath != "" {
		dataPathForSearch = *flags.ServerConfigDataPath
	}

	// Load config file
	filePath := findConfigFile(configPath, dataPathForSearch)
	if filePath != "" {
		log.Info("loading config file", "path", filePath)
		if err := loadConfigFile(filePath, cfg); err != nil {
			return nil, fmt.Errorf("failed to load config file: %w", err)
		}
	} else if configPath != "" {
		return nil, fmt.Errorf("config file not found: %s", configPath)
	}

	// Resolve the effective mode first (CLI/env > Config > Default)
	// We need this to apply mode-specific defaults correctly.
	// CLI and env both flow through flags.Mode (mflags' env tag handling
	// puts env values into the flags struct during FromStruct).
	var effectiveMode string
	if cfg.Mode != nil {
		effectiveMode = *cfg.Mode
	}
	if flags.Mode != nil && *flags.Mode != "" {
		effectiveMode = *flags.Mode
	}

	// Apply mode defaults based on the resolved mode
	// Only set if not already set (nil check)

	if effectiveMode == "standalone" {
		if cfg.Buildkit.StartEmbedded == nil {
			cfg.Buildkit.StartEmbedded = new(true)
		}
	}
	if effectiveMode == "standalone" {
		if cfg.Containerd.StartEmbedded == nil {
			cfg.Containerd.StartEmbedded = new(true)
		}
	}
	if effectiveMode == "standalone" {
		if cfg.Etcd.StartEmbedded == nil {
			cfg.Etcd.StartEmbedded = new(true)
		}
	}
	if effectiveMode == "standalone" {
		if cfg.Victorialogs.StartEmbedded == nil {
			cfg.Victorialogs.StartEmbedded = new(true)
		}
	}
	if effectiveMode == "standalone" {
		if cfg.Victoriametrics.StartEmbedded == nil {
			cfg.Victoriametrics.StartEmbedded = new(true)
		}
	}

	// Apply CLI flags (env values are already in flags via mflags env tags).
	applyCLIFlags(cfg, flags)

	// Post-process etcd configuration
	// If embedded etcd is enabled and no endpoints are specified, set default endpoint
	if cfg.Etcd.StartEmbedded != nil && *cfg.Etcd.StartEmbedded && len(cfg.Etcd.Endpoints) == 0 {
		port := 12379
		if cfg.Etcd.ClientPort != nil {
			port = *cfg.Etcd.ClientPort
		}
		cfg.Etcd.Endpoints = []string{fmt.Sprintf("http://127.0.0.1:%d", port)}
	}

	// Validate
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("configuration validation failed: %w", err)
	}

	return cfg, nil
}

func findConfigFile(explicitPath, dataPath string) string {
	if explicitPath != "" {
		if _, err := os.Stat(explicitPath); err == nil {
			return explicitPath
		}
		return ""
	}

	searchPaths := []string{
		"/etc/miren/server.toml",
		filepath.Join(dataPath, "config", "server.toml"),
	}

	for _, path := range searchPaths {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	return ""
}

func loadConfigFile(path string, cfg *Config) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	if err := toml.Unmarshal(data, cfg); err != nil {
		return fmt.Errorf("failed to parse TOML: %w", err)
	}

	return nil
}

func applyCLIFlags(cfg *Config, flags *CLIFlags) {

	if flags.AppVersionConfigRetentionCount != nil {
		cfg.AppVersion.RetentionCount = flags.AppVersionConfigRetentionCount
	}

	if flags.AppVersionConfigRetentionPeriod != nil && *flags.AppVersionConfigRetentionPeriod != "" {
		cfg.AppVersion.RetentionPeriod = flags.AppVersionConfigRetentionPeriod
	}

	if flags.BuildkitConfigGcKeepDuration != nil && *flags.BuildkitConfigGcKeepDuration != "" {
		cfg.Buildkit.GcKeepDuration = flags.BuildkitConfigGcKeepDuration
	}

	if flags.BuildkitConfigGcKeepStorage != nil && *flags.BuildkitConfigGcKeepStorage != "" {
		cfg.Buildkit.GcKeepStorage = flags.BuildkitConfigGcKeepStorage
	}

	if flags.BuildkitConfigSocketDir != nil && *flags.BuildkitConfigSocketDir != "" {
		cfg.Buildkit.SocketDir = flags.BuildkitConfigSocketDir
	}

	if flags.BuildkitConfigSocketPath != nil && *flags.BuildkitConfigSocketPath != "" {
		cfg.Buildkit.SocketPath = flags.BuildkitConfigSocketPath
	}

	if flags.BuildkitConfigStartEmbedded != nil {
		cfg.Buildkit.StartEmbedded = flags.BuildkitConfigStartEmbedded
	}

	if len(flags.Labs) > 0 {
		cfg.Labs = flags.Labs
	}

	if flags.Mode != nil && *flags.Mode != "" {
		cfg.Mode = flags.Mode
	}

	if flags.ContainerdConfigBinaryPath != nil && *flags.ContainerdConfigBinaryPath != "" {
		cfg.Containerd.BinaryPath = flags.ContainerdConfigBinaryPath
	}

	if flags.ContainerdConfigSocketPath != nil && *flags.ContainerdConfigSocketPath != "" {
		cfg.Containerd.SocketPath = flags.ContainerdConfigSocketPath
	}

	if flags.ContainerdConfigStartEmbedded != nil {
		cfg.Containerd.StartEmbedded = flags.ContainerdConfigStartEmbedded
	}

	if flags.EtcdConfigClientPort != nil {
		cfg.Etcd.ClientPort = flags.EtcdConfigClientPort
	}

	if len(flags.EtcdConfigEndpoints) > 0 {
		cfg.Etcd.Endpoints = flags.EtcdConfigEndpoints
	}

	if flags.EtcdConfigHTTPClientPort != nil {
		cfg.Etcd.HTTPClientPort = flags.EtcdConfigHTTPClientPort
	}

	if flags.EtcdConfigPeerPort != nil {
		cfg.Etcd.PeerPort = flags.EtcdConfigPeerPort
	}

	if flags.EtcdConfigPrefix != nil && *flags.EtcdConfigPrefix != "" {
		cfg.Etcd.Prefix = flags.EtcdConfigPrefix
	}

	if flags.EtcdConfigQuotaBackendBytes != nil {
		cfg.Etcd.QuotaBackendBytes = flags.EtcdConfigQuotaBackendBytes
	}

	if flags.EtcdConfigStartEmbedded != nil {
		cfg.Etcd.StartEmbedded = flags.EtcdConfigStartEmbedded
	}

	if flags.IngressConfigAddress != nil && *flags.IngressConfigAddress != "" {
		cfg.Ingress.Address = flags.IngressConfigAddress
	}

	if flags.IngressConfigMode != nil && *flags.IngressConfigMode != "" {
		cfg.Ingress.Mode = flags.IngressConfigMode
	}

	if flags.RemoteWriteConfigURL != nil && *flags.RemoteWriteConfigURL != "" {
		cfg.Metrics.RemoteWrite.URL = flags.RemoteWriteConfigURL
	}

	if flags.RemoteWriteConfigWorkloadIdentityAudience != nil && *flags.RemoteWriteConfigWorkloadIdentityAudience != "" {
		cfg.Metrics.RemoteWrite.WorkloadIdentityAudience = flags.RemoteWriteConfigWorkloadIdentityAudience
	}

	if flags.SagaConfigRetentionPeriod != nil && *flags.SagaConfigRetentionPeriod != "" {
		cfg.Saga.RetentionPeriod = flags.SagaConfigRetentionPeriod
	}

	if flags.SecretsConfigKeyRotationPeriod != nil && *flags.SecretsConfigKeyRotationPeriod != "" {
		cfg.Secrets.KeyRotationPeriod = flags.SecretsConfigKeyRotationPeriod
	}

	if flags.ServerConfigAddress != nil && *flags.ServerConfigAddress != "" {
		cfg.Server.Address = flags.ServerConfigAddress
	}

	if flags.ServerConfigConfigClusterName != nil && *flags.ServerConfigConfigClusterName != "" {
		cfg.Server.ConfigClusterName = flags.ServerConfigConfigClusterName
	}

	if flags.ServerConfigDataPath != nil && *flags.ServerConfigDataPath != "" {
		cfg.Server.DataPath = flags.ServerConfigDataPath
	}

	if flags.ServerConfigDiskMode != nil && *flags.ServerConfigDiskMode != "" {
		cfg.Server.DiskMode = flags.ServerConfigDiskMode
	}

	if flags.ServerConfigHTTPRequestTimeout != nil {
		cfg.Server.HTTPRequestTimeout = flags.ServerConfigHTTPRequestTimeout
	}

	if flags.ServerConfigReleasePath != nil && *flags.ServerConfigReleasePath != "" {
		cfg.Server.ReleasePath = flags.ServerConfigReleasePath
	}

	if flags.ServerConfigRunnerAddress != nil && *flags.ServerConfigRunnerAddress != "" {
		cfg.Server.RunnerAddress = flags.ServerConfigRunnerAddress
	}

	if flags.ServerConfigRunnerID != nil && *flags.ServerConfigRunnerID != "" {
		cfg.Server.RunnerID = flags.ServerConfigRunnerID
	}

	if flags.ServerConfigSkipClientConfig != nil {
		cfg.Server.SkipClientConfig = flags.ServerConfigSkipClientConfig
	}

	if flags.ServerConfigStopSandboxesOnShutdown != nil {
		cfg.Server.StopSandboxesOnShutdown = flags.ServerConfigStopSandboxesOnShutdown
	}

	if flags.TLSConfigAcmeDNSProvider != nil && *flags.TLSConfigAcmeDNSProvider != "" {
		cfg.TLS.AcmeDNSProvider = flags.TLSConfigAcmeDNSProvider
	}

	if flags.TLSConfigAcmeEmail != nil && *flags.TLSConfigAcmeEmail != "" {
		cfg.TLS.AcmeEmail = flags.TLSConfigAcmeEmail
	}

	if len(flags.TLSConfigAdditionalIPs) > 0 {
		cfg.TLS.AdditionalIPs = flags.TLSConfigAdditionalIPs
	}

	if len(flags.TLSConfigAdditionalNames) > 0 {
		cfg.TLS.AdditionalNames = flags.TLSConfigAdditionalNames
	}

	if flags.TLSConfigSelfSigned != nil {
		cfg.TLS.SelfSigned = flags.TLSConfigSelfSigned
	}

	if flags.TLSConfigStandardTLS != nil {
		cfg.TLS.StandardTLS = flags.TLSConfigStandardTLS
	}

	if flags.VictoriaLogsConfigAddress != nil && *flags.VictoriaLogsConfigAddress != "" {
		cfg.Victorialogs.Address = flags.VictoriaLogsConfigAddress
	}

	if flags.VictoriaLogsConfigHTTPPort != nil {
		cfg.Victorialogs.HTTPPort = flags.VictoriaLogsConfigHTTPPort
	}

	if flags.VictoriaLogsConfigRetentionPeriod != nil && *flags.VictoriaLogsConfigRetentionPeriod != "" {
		cfg.Victorialogs.RetentionPeriod = flags.VictoriaLogsConfigRetentionPeriod
	}

	if flags.VictoriaLogsConfigStartEmbedded != nil {
		cfg.Victorialogs.StartEmbedded = flags.VictoriaLogsConfigStartEmbedded
	}

	if flags.VictoriaMetricsConfigAddress != nil && *flags.VictoriaMetricsConfigAddress != "" {
		cfg.Victoriametrics.Address = flags.VictoriaMetricsConfigAddress
	}

	if flags.VictoriaMetricsConfigHTTPPort != nil {
		cfg.Victoriametrics.HTTPPort = flags.VictoriaMetricsConfigHTTPPort
	}

	if flags.VictoriaMetricsConfigRetentionPeriod != nil && *flags.VictoriaMetricsConfigRetentionPeriod != "" {
		cfg.Victoriametrics.RetentionPeriod = flags.VictoriaMetricsConfigRetentionPeriod
	}

	if flags.VictoriaMetricsConfigStartEmbedded != nil {
		cfg.Victoriametrics.StartEmbedded = flags.VictoriaMetricsConfigStartEmbedded
	}

}
