package: serverconfig

configs:
  Config:
    description: Complete server configuration from all sources
    fields:
      config_file:
        type: string
        description: "Path to configuration file"
        cli:
          long: config
          description: "Path to configuration file"
        cli_only: true  # This field is only for CLI, not stored in config
      mode:
        type: string
        default: standalone
        cli:
          long: mode
          short: m
          description: "Server mode: standalone (default), distributed (experimental)"
        env: MIREN_MODE
        toml: mode
        validation:
          enum: [standalone, distributed]

      server:
        type: ServerConfig
        toml: server
        nested: true

      tls:
        type: TLSConfig
        toml: tls
        nested: true

      etcd:
        type: EtcdConfig
        toml: etcd
        nested: true

      victorialogs:
        type: VictoriaLogsConfig
        toml: victorialogs
        nested: true

      victoriametrics:
        type: VictoriaMetricsConfig
        toml: victoriametrics
        nested: true

      containerd:
        type: ContainerdConfig
        toml: containerd
        nested: true

      buildkit:
        type: BuildkitConfig
        toml: buildkit
        nested: true

  ServerConfig:
    description: Core server settings
    fields:
      address:
        type: string
        default: :8443
        cli:
          long: address
          short: a
          description: Address to listen on (host:port). For IPv6 use brackets, e.g. "[::1]:8443".
        env: MIREN_SERVER_ADDRESS
        toml: address
        validation:
          format: host:port

      runner_address:
        type: string
        default: localhost:8444
        cli:
          long: runner-address
          description: Runner address (host:port). For IPv6 use brackets, e.g. "[::1]:8444".
        env: MIREN_SERVER_RUNNER_ADDRESS
        toml: runner_address
        validation:
          format: host:port

      data_path:
        type: string
        default: /var/lib/miren
        cli:
          long: data-path
          short: d
          description: Data path
        env: MIREN_SERVER_DATA_PATH
        toml: data_path

      runner_id:
        type: string
        default: miren
        cli:
          long: runner-id
          short: r
          description: Runner ID
        env: MIREN_SERVER_RUNNER_ID
        toml: runner_id

      release_path:
        type: string
        default: ""
        cli:
          long: release-path
          description: Path to release directory containing binaries
        env: MIREN_SERVER_RELEASE_PATH
        toml: release_path

      config_cluster_name:
        type: string
        default: local
        cli:
          long: config-cluster-name
          short: C
          description: Name of the cluster in client config
        env: MIREN_SERVER_CONFIG_CLUSTER_NAME
        toml: config_cluster_name

      skip_client_config:
        type: bool
        default: false
        cli:
          long: skip-client-config
          description: Skip writing client config file to clientconfig.d
        env: MIREN_SERVER_SKIP_CLIENT_CONFIG
        toml: skip_client_config

      http_request_timeout:
        type: int
        default: 60
        cli:
          long: http-request-timeout
          description: HTTP request timeout in seconds
        env: MIREN_SERVER_HTTP_REQUEST_TIMEOUT
        toml: http_request_timeout
        validation:
          min: 1

      stop_sandboxes_on_shutdown:
        type: bool
        default: false
        cli:
          long: stop-sandboxes-on-shutdown
          description: Stop all sandboxes when server shuts down (useful in development)
        env: MIREN_SERVER_STOP_SANDBOXES_ON_SHUTDOWN
        toml: stop_sandboxes_on_shutdown

  TLSConfig:
    description: TLS/certificate settings
    fields:
      additional_names:
        type: "[]string"
        default: []
        cli:
          long: dns-names
          description: Additional DNS names assigned to the server cert
        env: MIREN_TLS_ADDITIONAL_NAMES
        toml: additional_names

      additional_ips:
        type: "[]string"
        default: []
        cli:
          long: ips
          description: Additional IPs assigned to the server cert
        env: MIREN_TLS_ADDITIONAL_IPS
        toml: additional_ips
        validation:
          format: ip_list

      standard_tls:
        type: bool
        default: true
        cli:
          long: serve-tls
          description: Expose the http ingress on standard TLS ports
        env: MIREN_TLS_STANDARD_TLS
        toml: standard_tls

      acme_dns_provider:
        type: string
        default: ""
        cli:
          long: acme-dns-provider
          description: DNS provider for ACME DNS-01 challenges (e.g., cloudflare, route53, exec). When set, uses DNS challenge instead of HTTP challenge. See https://go-acme.github.io/lego/dns/ for available providers.
        env: MIREN_TLS_ACME_DNS_PROVIDER
        toml: acme_dns_provider

      acme_email:
        type: string
        default: ""
        cli:
          long: acme-email
          description: Email address for ACME account registration (recommended for account recovery and notifications)
        env: MIREN_TLS_ACME_EMAIL
        toml: acme_email

  EtcdConfig:
    description: Etcd configuration
    fields:
      endpoints:
        type: "[]string"
        default: []
        cli:
          long: etcd
          short: e
          description: Etcd endpoints
        env: MIREN_ETCD_ENDPOINTS
        toml: endpoints

      prefix:
        type: string
        default: /miren
        cli:
          long: etcd-prefix
          short: p
          description: Etcd prefix
        env: MIREN_ETCD_PREFIX
        toml: prefix

      start_embedded:
        type: bool
        cli:
          long: start-etcd
          description: Start embedded etcd server
        env: MIREN_ETCD_START_EMBEDDED
        toml: start_embedded
        mode_default:
          standalone: true

      client_port:
        type: int
        default: 12379
        cli:
          long: etcd-client-port
          description: Etcd client port
        env: MIREN_ETCD_CLIENT_PORT
        toml: client_port
        validation:
          port: true

      peer_port:
        type: int
        default: 12380
        cli:
          long: etcd-peer-port
          description: Etcd peer port
        env: MIREN_ETCD_PEER_PORT
        toml: peer_port
        validation:
          port: true

      http_client_port:
        type: int
        default: 12381
        cli:
          long: etcd-http-client-port
          description: Etcd HTTP client port
        env: MIREN_ETCD_HTTP_CLIENT_PORT
        toml: http_client_port
        validation:
          port: true

  VictoriaLogsConfig:
    description: VictoriaLogs configuration
    fields:
      start_embedded:
        type: bool
        cli:
          long: start-victorialogs
          description: Start embedded VictoriaLogs server
        env: MIREN_VICTORIALOGS_START_EMBEDDED
        toml: start_embedded
        mode_default:
          standalone: true

      http_port:
        type: int
        default: 9428
        cli:
          long: victorialogs-http-port
          description: VictoriaLogs HTTP port in embedded mode
        env: MIREN_VICTORIALOGS_HTTP_PORT
        toml: http_port
        validation:
          port: true

      retention_period:
        type: string
        default: "30d"
        cli:
          long: victorialogs-retention
          description: VictoriaLogs retention period (e.g. 30d, 2w, 1y)
        env: MIREN_VICTORIALOGS_RETENTION_PERIOD
        toml: retention_period
        validation:
          regex: '^\d+(ms|s|m|h|d|w|y)$'

      address:
        type: string
        default: "victorialogs:9428"
        cli:
          long: victorialogs-addr
          description: VictoriaLogs address (when not using embedded)
        env: MIREN_VICTORIALOGS_ADDRESS
        toml: address
        validation:
          format: host:port

  VictoriaMetricsConfig:
    description: VictoriaMetrics configuration
    fields:
      start_embedded:
        type: bool
        cli:
          long: start-victoriametrics
          description: Start embedded VictoriaMetrics server
        env: MIREN_VICTORIAMETRICS_START_EMBEDDED
        toml: start_embedded
        mode_default:
          standalone: true

      http_port:
        type: int
        default: 8428
        cli:
          long: victoriametrics-http-port
          description: VictoriaMetrics HTTP port in embedded mode
        env: MIREN_VICTORIAMETRICS_HTTP_PORT
        toml: http_port
        validation:
          port: true

      retention_period:
        type: string
        default: "1"
        cli:
          long: victoriametrics-retention
          description: VictoriaMetrics retention period in months
        env: MIREN_VICTORIAMETRICS_RETENTION_PERIOD
        toml: retention_period
        validation:
          regex: '^\d+$'

      address:
        type: string
        default: "victoriametrics:8428"
        cli:
          long: victoriametrics-addr
          description: VictoriaMetrics address (when not using embedded)
        env: MIREN_VICTORIAMETRICS_ADDRESS
        toml: address
        validation:
          format: host:port

  ContainerdConfig:
    description: Containerd configuration
    fields:
      start_embedded:
        type: bool
        cli:
          long: start-containerd
          description: Start embedded containerd daemon
        env: MIREN_CONTAINERD_START_EMBEDDED
        toml: start_embedded
        mode_default:
          standalone: true

      binary_path:
        type: string
        default: containerd
        cli:
          long: containerd-binary
          description: Path to containerd binary
        env: MIREN_CONTAINERD_BINARY_PATH
        toml: binary_path

      socket_path:
        type: string
        default: ""
        cli:
          long: containerd-socket
          description: Path to containerd socket
        env: MIREN_CONTAINERD_SOCKET_PATH
        toml: socket_path

  BuildkitConfig:
    description: BuildKit daemon configuration
    fields:
      start_embedded:
        type: bool
        cli:
          long: start-buildkit
          description: Start embedded BuildKit daemon for container image builds
        env: MIREN_BUILDKIT_START_EMBEDDED
        toml: start_embedded
        mode_default:
          standalone: true

      socket_path:
        type: string
        default: ""
        cli:
          long: buildkit-socket
          description: Path to external BuildKit Unix socket (for distributed mode)
        env: MIREN_BUILDKIT_SOCKET_PATH
        toml: socket_path

      socket_dir:
        type: string
        default: ""
        cli:
          long: buildkit-socket-dir
          description: Directory for embedded BuildKit Unix socket (defaults to data_path/buildkit/socket)
        env: MIREN_BUILDKIT_SOCKET_DIR
        toml: socket_dir

      gc_keep_storage:
        type: string
        default: "10GB"
        cli:
          long: buildkit-gc-storage
          description: Maximum BuildKit layer cache size (e.g., 10GB, 50GB)
        env: MIREN_BUILDKIT_GC_KEEP_STORAGE
        toml: gc_keep_storage

      gc_keep_duration:
        type: string
        default: "7d"
        cli:
          long: buildkit-gc-duration
          description: How long to keep BuildKit cache entries (e.g., 7d, 24h)
        env: MIREN_BUILDKIT_GC_KEEP_DURATION
        toml: gc_keep_duration
