apiVersion: miren.dev/rpc/v1
kind: IDL

imports:
  stream:
    path: ../pkg/rpc/stream/stream.yml
    import: miren.dev/runtime/pkg/rpc/stream
  standard:
    path: ../pkg/rpc/standard/standard.yml
    import: miren.dev/runtime/pkg/rpc/standard

types:
  - type: CpuUsage
    fields:
      - name: start
        type: standard.Timestamp
        index: 0
      - name: cores
        type: float64
        index: 1

  - type: MemoryUsage
    fields:
      - name: timestamp
        type: standard.Timestamp
        index: 0
      - name: bytes
        type: int64
        index: 1

  - type: PoolStatus
    fields:
      - name: name
        type: string
        index: 0
      - name: windows
        type: list
        element: "*WindowStatus"
        index: 1
      - name: idle
        type: int32
        index: 2
      - name: idleUsage
        type: int64
        index: 3

  - type: WindowStatus
    fields:
      - name: version
        type: string
        index: 0
      - name: leases
        type: int32
        index: 1
      - name: usage
        type: int64
        index: 2

  - type: ApplicationStatus
    fields:
      - name: name
        type: string
        index: 0
      - name: pools
        type: list
        element: "*PoolStatus"
        index: 1
      - name: lastMinCPU
        type: float64
        index: 2
      - name: lastHourCPU
        type: float64
        index: 3
      - name: lastDayCPU
        type: float64
        index: 4
      - name: cpuOverHour
        type: list
        element: '*CpuUsage'
        index: 5
      - name: memoryOverHour
        type: list
        element: '*MemoryUsage'
        index: 6
      - name: activeVersion
        type: string
        index: 7
      - name: lastDeploy
        type: standard.Timestamp
        index: 8

  - type: LogEntry
    fields:
      - name: timestamp
        type: standard.Timestamp
        index: 0
      - name: line
        type: string
        index: 1
      - name: stream
        type: string
        index: 2

interfaces:
  - name: AppInfo
    methods:
      - name: appInfo
        parameters:
          - name: application
            type: string
        results:
          - name: status
            type: ApplicationStatus

  - name: Logs
    methods:
      - name: appLogs
        parameters:
          - name: application
            type: string
          - name: from
            type: standard.Timestamp
          - name: follow
            type: bool
        results:
          - name: logs
            type: list
            element: LogEntry

