domain: dev.miren.schedule
version: v1alpha
attrs:
  key:
    type: component
    doc: The scheduling key for an entity
    indexed: true
    attrs:
      node:
        type: string
        doc: The node id the entity is scheduled for
      kind:
        type: keyword
        doc: The type of entity this is
  schedulable:
    type: bool
    doc: Indicates that the entity should be considered for scheduling
