services:
  postgres:
    image: oci.miren.cloud/postgres:16-alpine
    port: 5432
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: cloud

  valkey:
    image: oci.miren.cloud/valkey:8-alpine
    port: 6379

  etcd:
    image: oci.miren.cloud/etcd:v1
    port: 2379
    command:
      - etcd
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://etcd:2379
      - --initial-advertise-peer-urls
      - http://localhost:2380

  victorialogs:
    image: oci.miren.cloud/victoria-logs@sha256:47b820890d64c4575a2a0a46415dcd8a4fd59a0f1fcd6a377693d7aea639442e
    port: 9428

  victoriametrics:
    image: oci.miren.cloud/victoria-metrics:v1
    port: 8428
    command:
      - -storageDataPath=/victoria-metrics-data
      - -retentionPeriod=1
      - -httpListenAddr=:8428
      - -search.latencyOffset=2s
