apiVersion: miren.dev/rpc/v1
kind: IDL

types:
  - type: DiskStatus
    fields:
      - name: blocks_written
        type: int64
        index: 0
      - name: blocks_read
        type: int64
        index: 1
      - name: iops
        type: int64
        index: 2
      - name: segments_written
        type: int64
        index: 3

interfaces:
  - name: DiskManagement
    methods:
      - name: unmount
        parameters:
          - name: id
            type: string

      - name: status
        parameters:
          - name: id
            type: string
        results:
          - name: status
            type: DiskStatus
