domain: dev.miren.sandbox
version: v1alpha
attrs:
  labels:
    type: string
    doc: Label for the sandbox
    many: true

  hostNetwork:
    type: bool
    doc: |
      Indicates if the container should use the networking of
      node that it is running on directly

  network:
    type: component
    doc: Network accessability for the container
    many: true
    attrs:
      address:
        doc: A network address to reach the container at
        type: string
      subnet:
        doc: The subnet that the address is associated with
        type: string

  route:
    type: component
    doc: A network route the container uses
    many: true
    attrs:
      destination:
        doc: The network destination
        type: string
      gateway:
        doc: The next hop for the destination
        type: string

  port:
    type: component
    doc: A network port the container declares
    many: true
    attrs:
      port:
        type: int
        doc: Port number
        required: true
      name:
        type: string
        doc: Name of the port for reference
        required: true
      protocol:
        type: enum
        doc: Port protocol
        choices: [tcp, udp]
      type:
        type: string
        doc: The highlevel type of the port
        example: http
      node_port:
        type: int
        doc: The port number that should be forwarded from the node to the container

  volume:
    type: component
    doc: A volume that is available for binding into containers
    many: true
    attrs:
      name:
        type: string
        doc: The name of the volume
      provider:
        type: string
        doc: What provider should provide the volume
      labels:
        type: label
        doc: Labels that identify the volume to the provider
        many: true

  container:
    type: component
    doc: A container running in the sandbox
    many: true
    required: true
    attrs:
      image:
        type: string
        doc: Container image
        required: true
      name:
        type: string
        doc: Container name
      privileged:
        type: bool
        doc: Whether or not the container runs in privileged mode
      command:
        type: string
        doc: Command to run in the container
      directory:
        type: string
        doc: Directory to start in
      env:
        type: string
        doc: Environment variable for the container
        many: true
      mount:
        type: component
        doc: A mounted directory
        many: true
        attrs:
          source:
            type: string
            doc: Mount source path
          destination:
            type: string
            doc: Mount destination path

      oom_score:
        type: int
        doc: How to adjust the OOM score for this container
