/**
 * Docs lint script — validates that sidebars.ts and the docs filesystem are in sync.
 *
 * Checks:
 * 1. No sidebar_position frontmatter (ordering is controlled by sidebars.ts)
 * 2. Every hand-written doc file appears in sidebars.ts
 * 3. Every sidebar doc entry has a matching file on disk
 * 4. Admonitions follow the convention in docs/CLAUDE.md (valid type,
 *    bracket-form titles, no inline-bold callouts)
 *
 * Generated docs (commands, command/*) are excluded — they come from
 * command-sidebar.json which is generated by hack/gen-command-docs.
 */

import {readdirSync, readFileSync} from 'fs';
import {join, relative} from 'path';

const sidebars = (await import('./sidebars')).default;

const docsDir = join(import.meta.dirname, 'docs');
let errors = 0;

function fail(msg: string) {
  console.error(msg);
  errors++;
}

// --- Collect doc IDs from the filesystem ---

function walkDir(dir: string): string[] {
  const ids: string[] = [];
  for (const entry of readdirSync(dir, {withFileTypes: true})) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      ids.push(...walkDir(fullPath));
    } else if (entry.name.endsWith('.md')) {
      ids.push(relative(docsDir, fullPath).replace(/\.md$/, ''));
    }
  }
  return ids;
}

const fsIds = new Set(walkDir(docsDir));

// --- Collect doc IDs from sidebars.ts ---

const generatedPrefixes = ['commands', 'command/'];

function isGenerated(id: string): boolean {
  return generatedPrefixes.some((p) => id === p || id.startsWith(p));
}

type SidebarItem =
  | string
  | {type: 'doc'; id: string; [k: string]: unknown}
  | {type: 'category'; items: SidebarItem[]; link?: {type: 'doc'; id: string}; [k: string]: unknown}
  | {type: 'link'; [k: string]: unknown}
  | {type: 'ref'; id: string; [k: string]: unknown};

function extractDocIds(items: SidebarItem[]): string[] {
  const ids: string[] = [];
  for (const item of items) {
    if (typeof item === 'string') {
      ids.push(item);
    } else if (item.type === 'doc') {
      ids.push(item.id);
    } else if (item.type === 'ref') {
      ids.push(item.id);
    } else if (item.type === 'category') {
      if (item.link?.type === 'doc') {
        ids.push(item.link.id);
      }
      ids.push(...extractDocIds(item.items));
    }
    // 'link' type (external URLs) — skip
  }
  return ids;
}

const sidebarIds = new Set<string>();
for (const [, items] of Object.entries(sidebars)) {
  for (const id of extractDocIds(items as SidebarItem[])) {
    if (!isGenerated(id)) {
      sidebarIds.add(id);
    }
  }
}

// --- Check 1: No sidebar_position frontmatter ---

for (const id of fsIds) {
  const content = readFileSync(join(docsDir, `${id}.md`), 'utf-8');
  if (content.includes('sidebar_position')) {
    fail(`ERROR: sidebar_position found in docs/${id}.md — ordering is controlled by sidebars.ts`);
  }
}

// --- Check 2: Orphaned doc files (in filesystem but not in sidebar) ---

const orphaned = [...fsIds].filter((id) => !sidebarIds.has(id) && !isGenerated(id)).sort();
if (orphaned.length > 0) {
  fail(`ERROR: Doc files not listed in sidebars.ts:\n${orphaned.map((id) => `  ${id}`).join('\n')}`);
}

// --- Check 3: Missing doc files (in sidebar but not on filesystem) ---

const missing = [...sidebarIds].filter((id) => !fsIds.has(id)).sort();
if (missing.length > 0) {
  fail(`ERROR: Sidebar entries with no matching doc file:\n${missing.map((id) => `  ${id}`).join('\n')}`);
}

// --- Check 4: Admonition style (see docs/CLAUDE.md) ---

const ALLOWED_ADMONITIONS = new Set(['note', 'tip', 'info', 'warning', 'danger']);

// A line whose first non-list-marker content is a bold admonition keyword acting
// as a label, e.g. **NOTE:**, **Warning**:, - **important:** — these masquerade
// as admonitions and should be real ::: blocks. Case-insensitive, and tolerant of
// leading indentation and list/blockquote markers.
const INLINE_CALLOUT =
  /^\s*(?:[-*+]\s+|\d+\.\s+|>\s*)*\*\*(note|warning|important|tip|caution|danger|info)(\*\*)?:/i;

// Opening code fence: >=3 backticks or tildes, optionally indented, optional info string.
const FENCE = /^(\s*)(`{3,}|~{3,})(.*)$/;
// Admonition opener (":::note[...]") and bare closer (":::" alone on the line).
const ADMONITION_OPEN = /^\s*:::([a-zA-Z]+)(.*)$/;
const ADMONITION_CLOSE = /^\s*:::\s*$/;

for (const id of fsIds) {
  if (isGenerated(id)) continue;
  const lines = readFileSync(join(docsDir, `${id}.md`), 'utf-8').split('\n');

  let fenceChar = '';
  let fenceLen = 0;
  let inFence = false;
  let openAdmonition: string | null = null; // loc of an admonition awaiting its close

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const loc = `docs/${id}.md:${i + 1}`;

    // Track fenced code blocks so we don't lint example markup. Close only on a
    // matching delimiter (same char, at least as long) so a stray or shorter
    // marker inside a longer fence can't end the block early.
    const fence = line.match(FENCE);
    if (fence) {
      const marker = fence[2];
      if (!inFence) {
        inFence = true;
        fenceChar = marker[0];
        fenceLen = marker.length;
      } else if (marker[0] === fenceChar && marker.length >= fenceLen && fence[3].trim() === '') {
        inFence = false;
      }
      continue;
    }
    if (inFence) continue;

    if (INLINE_CALLOUT.test(line)) {
      fail(
        `ERROR: ${loc} — inline-bold callout "${line.trim().slice(0, 40)}"; ` +
          `use a :::note/:::tip/:::info/:::warning/:::danger admonition instead`,
      );
    }

    const opener = line.match(ADMONITION_OPEN);
    if (opener) {
      const type = opener[1].toLowerCase();
      const rest = opener[2];
      if (!ALLOWED_ADMONITIONS.has(type)) {
        const hint = type === 'caution' ? ' (":::caution" is deprecated → ":::warning")' : '';
        fail(
          `ERROR: ${loc} — "${type}" is not an allowed admonition type; ` +
            `use note, tip, info, warning, or danger${hint}`,
        );
      } else if (!/^\[[^\]]+\]\s*$/.test(rest)) {
        // Require a bracketed title. Distinguish the failure modes for a clearer message.
        if (rest.trim() === '') {
          fail(`ERROR: ${loc} — admonition ":::${type}" needs a bracketed title, e.g. ":::${type}[Title]"`);
        } else if (rest.trimStart().startsWith('[')) {
          fail(`ERROR: ${loc} — malformed admonition title "${rest.trim()}"; use ":::${type}[Title]"`);
        } else {
          fail(
            `ERROR: ${loc} — space-form admonition title; ` +
              `use bracket syntax ":::${type}[${rest.trim()}]"`,
          );
        }
      }
      if (openAdmonition) {
        fail(`ERROR: ${openAdmonition} — admonition is missing its closing ":::"`);
      }
      openAdmonition = loc;
      continue;
    }

    if (ADMONITION_CLOSE.test(line)) {
      openAdmonition = null;
    }
  }

  if (openAdmonition) {
    fail(`ERROR: ${openAdmonition} — admonition is missing its closing ":::"`);
  }
}

// --- Check 5: No site-absolute links between docs pages ---

// A site-absolute link resolves against whatever docs version is served at the
// site root, so from /next (main) it silently sends the reader into the
// released docs. Relative .md links resolve within their own version.
// Site-absolute links to static assets (/img/..., /*.json) are fine.
// CommonMark allows an optional title after the destination, as in
// [CLI](/commands "CLI Reference"), so the destination is not always
// followed directly by the closing paren.
const ABSOLUTE_LINK =
  /\]\((\/[A-Za-z0-9][^)\s]*?)(?:#[^)\s]*)?(?:\s+(?:"[^"]*"|'[^']*'|\([^)]*\)))?\)/g;

function resolvesToDoc(target: string): boolean {
  // Docusaurus serves /secrets?view=full as the secrets page, so the query
  // has to come off before the path can be matched against a doc id.
  const rel = target.replace(/\?.*$/, '').replace(/^\//, '');
  return fsIds.has(rel) || fsIds.has(`${rel}/index`);
}

for (const id of fsIds) {
  const lines = readFileSync(join(docsDir, `${id}.md`), 'utf-8').split('\n');
  for (let i = 0; i < lines.length; i++) {
    for (const m of lines[i].matchAll(ABSOLUTE_LINK)) {
      if (!resolvesToDoc(m[1])) continue;
      fail(
        `ERROR: docs/${id}.md:${i + 1} — site-absolute link "${m[1]}" to another docs page; ` +
          `use a relative .md link so it resolves within its own docs version`,
      );
    }
  }
}

// --- Result ---

if (errors === 0) {
  console.log('✓ docs lint passed');
} else {
  process.exit(1);
}
