domain: dev.miren.core
version: v1alpha
kinds:
  metadata:
    name:
      type: string
      doc: The name of the entity
    project:
      type: ref
      doc: A reference to the project the entity belongs to
    labels:
      type: label
      doc: Identifying labels for the entity
      many: true

  project:
    owner:
      type: string
      doc: The email address of the project owner

  app:
    project:
      type: ref
      doc: The project that the app belongs to

    active_version:
      type: ref
      doc: The version of the project that should be used

  artifact:
    app:
      type: ref
      doc: The application the artifact is for

    manifest:
      type: string
      doc: The OCI image manifest for the version

    manifest_digest:
      type: string
      doc: The digest of the manifest
      indexed: true

  app_version:
    app:
      type: ref
      doc: The application the version is for
    version:
      type: string
      doc: The version of this app

    image_url:
      type: string
      doc: The OCI url for the versions code

    artifact:
      type: ref
      doc: The artifact to deploy for the version

    manifest:
      type: string
      doc: The OCI image manifest for the version

    manifest_digest:
      type: string
      doc: The digest of the manifest
      indexed: true

    config:
      type: component
      doc: The configuration of the version
      attrs:
        port:
          type: int
          doc: The TCP port to access, default to 3000
        services:
          type: component
          doc: Per-service configuration including concurrency controls
          many: true
          attrs:
            name:
              type: string
              doc: The service name (e.g. web, worker)
            image:
              type: string
              doc: Optional container image for this service (e.g. postgres:16). If not specified, uses the app-level built image.
            env:
              type: component
              doc: Environment variables for this service only
              many: true
              attrs:
                key:
                  type: string
                  doc: The name of the variable
                value:
                  type: string
                  doc: The value of the variable
                sensitive:
                  type: bool
                  doc: Whether or not the value is sensitive
            service_concurrency:
              type: component
              doc: Concurrency configuration for this service
              attrs:
                mode:
                  type: string
                  doc: The concurrency mode (auto or fixed)
                requests_per_instance:
                  type: int
                  doc: For auto mode, number of concurrent requests per instance
                scale_down_delay:
                  type: string
                  doc: For auto mode, delay before scaling down idle instances (e.g. 2m, 15m)
                num_instances:
                  type: int
                  doc: For fixed mode, number of instances to maintain
        entrypoint:
          type: string
          doc: The container entrypoint command
        commands:
          type: component
          doc: The command to run for a specific service type
          many: true
          attrs:
            service:
              type: string
              doc: The service name
            command:
              type: string
              doc: The command to run for the service
        variable:
          type: component
          doc: A variable to be exposed to the app
          many: true
          attrs:
            key:
              type: string
              doc: The name of the variable
            value:
              type: string
              doc: The value of the value
            sensitive:
              type: bool
              doc: Whether or not the value is sensitive

  deployment:
    app_name:
      type: string
      doc: The name of the app being deployed
      indexed: true
    
    app_version:
      type: string
      doc: The app version ID or temporary value (pending-build, failed-{id})
    
    cluster_id:
      type: string
      doc: The cluster where the deployment is happening
      indexed: true
    
    status:
      type: string
      doc: Deployment status (in_progress, active, failed, rolled_back)
      indexed: true
    
    phase:
      type: string
      doc: Current phase of deployment (preparing, building, pushing, activating)
    
    deployed_by:
      type: component
      doc: Information about who initiated the deployment
      attrs:
        user_id:
          type: string
          doc: The ID of the user who deployed
        user_email:
          type: string
          doc: The email of the user who deployed
        timestamp:
          type: string
          doc: When the deployment was initiated (RFC3339 format)
    
    completed_at:
      type: string
      doc: When the deployment was completed (RFC3339 format)
    
    error_message:
      type: string
      doc: Error message if deployment failed
    
    build_logs:
      type: string
      doc: Build logs concatenated with newlines (especially useful for failed deployments)
      
    git_info:
      type: component
      doc: Git information at time of deployment
      attrs:
        sha:
          type: string
          doc: Git commit SHA
        branch:
          type: string
          doc: Git branch name
        message:
          type: string
          doc: Git commit message
        author:
          type: string
          doc: Git commit author
        is_dirty:
          type: bool
          doc: Whether working tree had uncommitted changes
        working_tree_hash:
          type: string
          doc: Hash of working tree if dirty
        commit_author_email:
          type: string
          doc: Git commit author email address
        commit_timestamp:
          type: string
          doc: Git commit timestamp in RFC3339 format
        repository:
          type: string
          doc: Git repository remote URL


