domain: dev.miren.core
version: v1alpha
kinds:
  metadata:
    name:
      type: string
      doc: The name of the entity
    project:
      type: ref
      doc: A reference to the project the entity belongs to
    labels:
      type: label
      doc: Identifying labels for the entity
      many: true

  project:
    owner:
      type: string
      doc: The email address of the project owner

  app:
    project:
      type: ref
      doc: The project that the app belongs to

    active_version:
      type: ref
      doc: The version of the project that should be used

  artifact:
    app:
      type: ref
      doc: The application the artifact is for

    manifest:
      type: string
      doc: The OCI image manifest for the version

    manifest_digest:
      type: string
      doc: The digest of the manifest
      indexed: true

  app_version:
    app:
      type: ref
      doc: The application the version is for
      indexed: true

    version:
      type: string
      doc: The version of this app

    image_url:
      type: string
      doc: The OCI url for the versions code

    artifact:
      type: ref
      doc: The artifact to deploy for the version

    manifest:
      type: string
      doc: The OCI image manifest for the version

    manifest_digest:
      type: string
      doc: The digest of the manifest
      indexed: true

    config:
      type: component
      doc: The configuration of the version
      attrs:
        port:
          type: int
          doc: The TCP port to access, default to 3000
        concurrency:
          type: component
          doc: How to control the concurrency for the application
          attrs:
            requests_per_instance:
              type: int
              doc: How many simultaneous requests this app can handle. An additional copy will be launched when more than this number of requests comes in concurrently. Defaults to 0 (unlimited concurrency, no auto scale up).
            min_instances:
              type: int
              doc: The minimum number of warm copies of the app to keep running. Defaults to 0.
            max_instances:
              type: int
              doc: The maximum number of copies to launch. Defaults to 0, which means no limit.
            scale_down_delay:
              type: duration
              doc: How long to wait before shutting down an idle instance. An instance is considered idle when it's not handling any requests. Defaults to 2 minutes.
        entrypoint:
          type: string
          doc: The container entrypoint command
        commands:
          type: component
          doc: The command to run for a specific service type
          many: true
          attrs:
            service:
              type: string
              doc: The service name
            command:
              type: string
              doc: The command to run for the service
        variable:
          type: component
          doc: A variable to be exposed to the app
          many: true
          attrs:
            key:
              type: string
              doc: The name of the variable
            value:
              type: string
              doc: The value of the value
            sensitive:
              type: bool
              doc: Whether or not the value is sensitive


